version: '3'

services:
  MySQL:
    hostname: 'mysql'
    image: mysql:5.7    
    expose:
      "3306"
    volumes:
      - data_MySQL:/var/lib/mysql
    networks: 
      -ReverseProxy

    environment:
      MYSQL_ROOT_PASSWORD: d79KvYFGPSde7tHW
      MYSQL_DATABASE: base
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: yibzsyefdgsigrjw

    container_name: MySQL

    restart: always

phpmyadmin:
  image: phpmyadmin/phpmyadmin
     
  expose:
    - "80"

  networks: 
    -ProxyTargetNetwork
  environment:
    PMA_ARBITRARY: 1
    MYSQL_USER: phpmyadmin
    MYSQL_PASSWORD: yibzsyefdgsigrjw
    MYSQL_ROOT_PASSWORD: d79KvYFGPSde7tHW
  links:
    # for mysql container
    - "MySQL:MySQL"

volumes:
    data_MySQL:
      external: 
        name: mysql

        
networks: 
  ReverseProxy:
    external:
      name: ProxyTargetNetwork