version: '2'

services:
  MySQL:
    hostname: 'mysql'
    image: mysql:5.7    
    expose:
      - "3306"
    volumes:
      - data_MySQL:/var/lib/mysql
    networks: 
      - ReverseProxy:
          ipv4_address: 172.0.10.0

    environment:
      MYSQL_ROOT_PASSWORD: 9rriyx
      MYSQL_DATABASE: base
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: ne4cbm

    container_name: MySQL

    restart: always

  Adminer:
    image: adminer
      
    expose:
      - "8080"

    networks: 
      - ReverseProxy:
          ipv4_address: 172.0.10.1

    environment:
        - ADMINER_DESIGN=pepa-linha
        - ADMINER_DEFAULT_SERVER=MySQL
    links:
      # for mysql container
      - "MySQL:MySQL"

    container_name: Adminer

volumes:
  data_MySQL:
    external: 
      name: mysql

        
networks: 
  ReverseProxy:
    external:
      name: ProxyTargetNetwork