version: '2'

services:
  Adminer:
    image: adminer
      
    expose:
      - "8080"

    networks: 
      - ReverseProxy
    # environment:
    #   PMA_ARBITRARY: 1
    #   MYSQL_USER: phpmyadmin
    #   MYSQL_PASSWORD: ne4cbm
    #   MYSQL_ROOT_PASSWORD: 9rriyx

    environment: 
      ADMINER_DESIGN='pepa-linha'

    links:
      # for mysql container
      - "MySQL:MySQL"

volumes:
  data_MySQL:
    external: 
      name: mysql

        
networks: 
  ReverseProxy:
    external:
      name: ProxyTargetNetwork