version: '2'

services:
  db:
    image: mysql:5.7
    
    volumes:
      - /data/db:/var/lib/mysql

    expose:
      "3306"

    network_mode: "bridge"
    networks: 
      -ProxyTargetNetwork

    environment:
      MYSQL_ROOT_PASSWORD: d79KvYFGPSde7tHW
      MYSQL_DATABASE: base
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: yibzsyefdgsigrjw

    restart: always

phpmyadmin:
  image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: yibzsyefdgsigrjw
            MYSQL_ROOT_PASSWORD: d79KvYFGPSde7tHW
     expose:
            - "80"

    network_mode: "bridge"
      networks: 
        -ProxyTargetNetwork
  
     links:
            # for mysql container
            - "db:db"
volumes:
    db: