version: '2'

services:
  portainer:
    image: portainer/portainer
    expose:
      - "9000"

    network_mode: "bridge"
     networks: 
      -ProxyTargetNetwork

    command: -H unix:///var/run/docker.sock
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: Portainer



volumes:
  portainer_data: