version: '2'

services:
  Adminer:
    image: adminer
      
    ports:
      - "8080:8080"

    networks: 
      - ReverseProxy
    environment:
        - ADMINER_DESIGN=pepa-linha
        - ADMINER_DEFAULT_SERVER=De
    links:
      # for mysql container
      - "MySQL:MySQL"

    container_name: Adminer


volumes:
  data_MySQL:
    external: 
      name: mysql

        
networks: 
  ReverseProxy:
    external:
      name: ProxyTargetNetwork